[
  {
    id: 'sub_1OjSG5C7rML7LYwFgcOxo9zT',
    object: 'subscription',
    application: null,
    application_fee_percent: null,
    automatic_tax: { enabled: true, liability: [Object] },
    billing_cycle_anchor: 1707854833,
    billing_cycle_anchor_config: null,
    billing_thresholds: null,
    cancel_at: null,
    cancel_at_period_end: false,
    canceled_at: null,
    cancellation_details: {
      comment: null, feedback:
        null, reason: null
    },
    collection_method: 'charge_automatically',
    created: 1707854833,
    currency: 'eur',
    current_period_end: 1710360433,
    current_period_start: 1707854833,
    customer: 'cus_P0pZPUce9ljhFV',
    days_until_due: null,
    default_payment_method: 'pm_1OCnugC7rML7LYwF6jOqaqAk',
    default_source: null,
    default_tax_rates: [],
    description: null,
    discount: null,
    ended_at: null,
    invoice_settings: { account_tax_ids: null, issuer: [Object] },
    items: {
      object: 'list',
      data: [Array],
      has_more: false,
      total_count: 1,
      url: '/v1/subscription_items?subscription=sub_1OjSG5C7rML7LYwFgcOxo9zT'
    },
    latest_invoice: 'in_1OjSG5C7rML7LYwFp0QtYnJD',
    livemode: false,
    metadata: {},
    next_pending_invoice_item_invoice: null,
    on_behalf_of: null,
    pause_collection: null,
    payment_settings: {
      payment_method_options: null,
      payment_method_types: null,
      save_default_payment_method: 'off'
    },
    pending_invoice_item_interval: null,
    pending_setup_intent: null,
    pending_update: null,
    plan: {
      id: 'price_1OCnQOC7rML7LYwFmAVpwb7h',
      object: 'plan',
      active: true,
      aggregate_usage: null,
      amount: 3000,
      amount_decimal: '3000',
      billing_scheme: 'per_unit',
      created: 1700071372,
      currency: 'eur',
      interval: 'month',
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: null,
      product: 'prod_P0p4PVttcIjgnx',
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: 'licensed'
    },
    quantity: 1,
    schedule: null,
    start_date: 1707854833,
    status: 'active',
    test_clock: 'clock_1OlcWwC7rML7LYwFssP0cNQE',
    transfer_data: null,
    trial_end: null,
    trial_settings: { end_behavior: [Object] },
    trial_start: null
  }
]